### ISSUE TITLE
Training on dataset doesn't work

### ISSUE THREAD

**Issue by devqueue** [devqueue/Skyhawk-cli#8]
Training on given faces doesn't work
Here is the error
```
Traceback (most recent call last):
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/bin/skyhawk", line 33, in <module>
    sys.exit(load_entry_point('skyhawk', 'console_scripts', 'skyhawk')())
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/skyhawk/commands/cmd_train.py", line 8, in cli
    result = trainer.Facetrainer()
  File "/home/smokedpirate/Documents/dev/Python/Skyhawk-cli/skyhawk/services/trainer.py", line 50, in Facetrainer
    recognizer.train(x_train, np.array(y_labels))
cv2.error: OpenCV(3.4.8) /io/opencv_contrib/modules/face/src/lbph_faces.cpp:362: error: (-210:Unsupported format or combination of formats) Empty training data was given. You'll need more than one sample to learn a model. in function 'train'
```

**Comment by devqueue** [comment]
A pull request has been made #16 to temporarily fix this issue but this will be taken into longterm consideration
